---
- hosts: all
  remote_user: root
  tasks:
    - name: Add epel-release repository
      yum:
        name: epel-release
        state: present
    - name: Install nginx
      yum:
        name: nginx
        state: present
    - name: Insert index.html page
      template:
        src: index.html
        dest: /usr/share/nginx/index.html
    - name: Configure firewall
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Firewalld reload
      command: firewall-cmd --reload
    - name: Start nginx
      service:
          name: nginx
          state: started
